name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install datasets huggingface_hub pandas
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/data_registration.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install Dependencies
        run: |
          pip install datasets pandas scikit-learn huggingface_hub
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/data_preparation/data_preparation.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install mlflow scikit-learn xgboost lightgbm datasets transformers huggingface_hub joblib pandas
      - name: Start MLflow Server # This is for local tracking, for remote tracking, you'd configure MLFLOW_TRACKING_URI
        run: |
          # nohup mlflow ui --host 0.0.0.0 --port 5000 &  # Run MLflow UI in the background - Commented out
          # sleep 5  # Wait for a moment to let the server start - Commented out
          echo "MLflow UI server typically not run in GitHub Actions. Configure MLFLOW_TRACKING_URI for remote tracking." # Added informative message
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_training/model_training.py

  deploy-hosting:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    needs: [model-training,data-prep,register-dataset]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install datasets huggingface_hub
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_REPO_ID: nareshpaib/tourism-prediction-app
          HF_MODEL_REPO_ID: nareshpaib/tourism_classifier
        run: |
          python tourism_project/deployment/deploy.py
